title: Hello Jekyll
description: 描述
#remote_theme: pages-themes/tactile@v0.2.0
#remote_theme: riggraz/no-style-please
remote_theme: cotes2020/jekyll-theme-chirpy
#theme: jekyll-theme-chirpys
#remote_theme: just-the-docs/just-the-docs

# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
